// design/components/core/PodiumCard.jsx
import React from 'react';
import { VerdictSplitBar } from './VerdictSplitBar';
const RANK = [
  { label: 'NO.1 — DEAD-EYE', color: 'var(--verdict-ai)', score: 'var(--verdict-ai)', border: 'var(--verdict-ai)' },
  { label: 'NO.2', color: 'var(--fg-muted)', score: 'var(--fg-1)', border: 'var(--line)' },
  { label: 'NO.3', color: 'var(--fg-muted)', score: 'var(--fg-1)', border: 'var(--line)' }
];
export function PodiumCard({ rank = 1, handle, score, checks, ai, mixed, human, lastAt }) {
  const r = RANK[Math.min(Math.max(rank, 1), 3) - 1];
  return (
    <div style={{ border: '1px solid ' + r.border, borderRadius: 6, padding: '1.25rem 1.25rem 1rem', background: 'var(--bg-1)' }}>
      <span style={{ fontFamily: 'var(--font-mono)', fontSize: '0.72rem', color: r.color, letterSpacing: '0.1em' }}>{r.label}</span>
      <div style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', gap: '0.75rem', margin: '0.3rem 0 0.8rem' }}>
        <a href="#" style={{ fontWeight: 700, fontSize: '1.1rem', color: 'var(--fg-1)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>@{handle}</a>
        <span style={{ fontFamily: 'var(--font-mono)', fontSize: '1.7rem', fontWeight: 600, fontVariantNumeric: 'tabular-nums', color: r.score }}>{score}</span>
      </div>
      <VerdictSplitBar ai={ai} mixed={mixed} human={human} />
      <span style={{ fontFamily: 'var(--font-mono)', fontSize: '0.72rem', color: 'var(--fg-muted)', display: 'block', marginTop: '0.6rem' }}>{checks} checks · {ai} AI / {mixed} mixed / {human} human · {lastAt}</span>
    </div>
  );
}

// src/lib/PodiumCard.svelte
<script lang="ts">
	import VerdictSplitBar from '$lib/VerdictSplitBar.svelte';
	import { formatScore, timeAgo } from '$lib/format';

	let {
		rank,
		handle,
		score,
		checks,
		ai,
		mix,
		human,
		lastAt
	}: {
		rank: 1 | 2 | 3;
		handle: string;
		score: number;
		checks: number;
		ai: number;
		mix: number;
		human: number;
		lastAt: number;
	} = $props();

	const RANK = [
		{ label: 'NO.1 — DEAD-EYE', color: 'var(--verdict-ai)', border: 'var(--verdict-ai)' },
		{ label: 'NO.2', color: 'var(--verdict-mixed)', border: 'var(--line)' },
		{ label: 'NO.3', color: 'var(--verdict-human)', border: 'var(--line)' }
	];
	const r = $derived(RANK[Math.min(Math.max(rank, 1), 3) - 1]);
</script>

<div class="card" style="border-color:{r.border}">
	<span class="rank mono" style="color:{r.color}">{r.label}</span>
	<div class="row">
		<a href="/u/{handle}" class="handle">@{handle}</a>
		<span class="score mono" style="color:{r.color}">{formatScore(score)}</span>
	</div>
	<VerdictSplitBar {ai} {mix} {human} />
	<span class="meta mono">{checks} checks · {ai} AI / {mix} mixed / {human} human · {timeAgo(lastAt)}</span>
</div>

<style>
	.card {
		border: 1px solid var(--line);
		border-radius: 6px;
		padding: 1.25rem 1.25rem 1rem;
		background: var(--bg-1);
	}
	.rank {
		font-size: 0.72rem;
		letter-spacing: 0.1em;
	}
	.row {
		display: flex;
		align-items: baseline;
		justify-content: space-between;
		gap: 0.75rem;
		margin: 0.3rem 0 0.8rem;
	}
	.handle {
		font-weight: 700;
		font-size: 1.1rem;
		color: var(--fg-1);
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}
	.score {
		font-size: 1.7rem;
		font-weight: 600;
		font-variant-numeric: tabular-nums;
	}
	.meta {
		font-size: 0.72rem;
		color: var(--fg-muted);
		display: block;
		margin-top: 0.6rem;
	}
</style>
