// design/components/core/VerdictBadge.jsx
import React from 'react';
const C = { ai: 'var(--verdict-ai)', mixed: 'var(--verdict-mixed)', human: 'var(--verdict-human)' };
const L = { ai: 'AI', mixed: 'Mixed', human: 'Human' };
export function VerdictBadge({ verdict = 'ai' }) {
  const c = C[verdict] || C.ai;
  return <span style={{ fontFamily: 'var(--font-mono)', minWidth: '4.2rem', textAlign: 'center', padding: '0.05rem 0.4rem', borderRadius: 3, fontSize: '0.68rem', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.06em', border: '1px solid ' + c, color: c, display: 'inline-block', boxSizing: 'border-box' }}>{L[verdict] || verdict}</span>;
}

// src/lib/VerdictBadge.svelte
<script lang="ts">
	import { verdictMeta } from '$lib/format';

	let { verdict }: { verdict: string } = $props();

	const meta = $derived(verdictMeta(verdict));
</script>

<span class="badge mono {meta.className}">{meta.label}</span>

<style>
	.badge {
		display: inline-block;
		box-sizing: border-box;
		min-width: 4.2rem;
		text-align: center;
		padding: 0.05rem 0.4rem;
		border-radius: 3px;
		font-size: 0.68rem;
		font-weight: 600;
		text-transform: uppercase;
		letter-spacing: 0.06em;
		flex: none;
		/* Color comes from the global .v-* class; the border just follows it. */
		border: 1px solid currentColor;
	}
	.badge:not([class*='v-']) {
		border-color: var(--line);
	}
</style>
