// design/components/core/VerdictSplitBar.jsx
import React from 'react';
export function VerdictSplitBar({ ai = 0, mixed = 0, human = 0, height = 6 }) {
  const t = ai + mixed + human || 1;
  const seg = (n, v) => <span key={v} style={{ background: 'var(--verdict-' + v + ')', width: (100 * n / t) + '%' }} />;
  return <div style={{ display: 'flex', height, borderRadius: height / 2, overflow: 'hidden' }}>{seg(ai, 'ai')}{seg(mixed, 'mixed')}{seg(human, 'human')}</div>;
}

// src/lib/VerdictSplitBar.svelte
<script lang="ts">
	let {
		ai = 0,
		mix = 0,
		human = 0,
		height = 6
	}: { ai?: number; mix?: number; human?: number; height?: number } = $props();

	const total = $derived(ai + mix + human || 1);
</script>

<div class="bar" style="height:{height}px;border-radius:{height / 2}px" aria-hidden="true">
	<span style="background:var(--verdict-ai);width:{(100 * ai) / total}%"></span>
	<span style="background:var(--verdict-mixed);width:{(100 * mix) / total}%"></span>
	<span style="background:var(--verdict-human);width:{(100 * human) / total}%"></span>
</div>

<style>
	.bar {
		display: flex;
		overflow: hidden;
	}
</style>
