// src/lib/StatBlock.svelte
<script lang="ts">
	let {
		value,
		label,
		accent = 'var(--verdict-ai)'
	}: { value: string; label: string; accent?: string } = $props();
</script>

<div class="stat">
	<span class="num" style="border-top-color:{accent}">{value}</span>
	<span class="lbl">{label}</span>
</div>

<style>
	.stat {
		font-family: var(--font-mono);
	}
	.num {
		display: block;
		font-size: 2.4rem;
		font-weight: 600;
		font-variant-numeric: tabular-nums;
		border-top: 3px solid var(--verdict-ai);
		padding-top: 0.4rem;
	}
	.lbl {
		color: var(--fg-muted);
		font-size: 0.75rem;
		text-transform: uppercase;
		letter-spacing: 0.08em;
	}
</style>

// design/components/core/StatBlock.jsx
import React from 'react';
export function StatBlock({ value, label, accent = 'var(--verdict-ai)' }) {
  return (
    <div style={{ fontFamily: 'var(--font-mono)' }}>
      <span style={{ display: 'block', fontSize: '2.4rem', fontWeight: 600, fontVariantNumeric: 'tabular-nums', borderTop: '3px solid ' + accent, paddingTop: '0.4rem' }}>{value}</span>
      <span style={{ color: 'var(--fg-muted)', fontSize: '0.75rem', textTransform: 'uppercase', letterSpacing: '0.08em' }}>{label}</span>
    </div>
  );
}
